import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

main(){
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        appBar: AppBar(
          centerTitle: true,
          title: const Text('List Tile'),
        ),
        body: ListView(
          children: const [
            ListTile(
              title: Text('Gayuh Widyanata'),
              subtitle: Text('Hai Apa Kabar?ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd',
              maxLines: 2,
              overflow: TextOverflow.ellipsis,),
              leading: CircleAvatar(),
              trailing: Text('10.20'),
              dense: true,
              tileColor: Colors.green,
              // contentPadding: EdgeInsets.symmetric(vertical: 20),
            ),
            Divider(color: Colors.black),
            ListTile(
              title: Text('Gayuh Widyanata'),
              subtitle: Text('Hai Apa Kabar?ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd',
              maxLines: 2,
              overflow: TextOverflow.ellipsis,),
              leading: CircleAvatar(),
              trailing: Text('10.20'),
              dense: true,
              tileColor: Colors.green,
              // contentPadding: EdgeInsets.symmetric(vertical: 20),
            ),
            Divider(color: Colors.black),
            ListTile(
              title: Text('Gayuh Widyanata'),
              subtitle: Text('Hai Apa Kabar?ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd',
              maxLines: 2,
              overflow: TextOverflow.ellipsis,),
              leading: CircleAvatar(),
              trailing: Text('10.20'),
              dense: true,
              tileColor: Colors.green,
              // contentPadding: EdgeInsets.symmetric(vertical: 20),
            ),
            Divider(color: Colors.black),
            ListTile(
              title: Text('Gayuh Widyanata'),
              subtitle: Text('Hai Apa Kabar?ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd',
              maxLines: 2,
              overflow: TextOverflow.ellipsis,),
              leading: CircleAvatar(),
              trailing: Text('10.20'),
              dense: true,
              tileColor: Colors.green,
              // contentPadding: EdgeInsets.symmetric(vertical: 20),
            ),
            Divider(color: Colors.black),
            ListTile(
              title: Text('Gayuh Widyanata'),
              subtitle: Text('Hai Apa Kabar?ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd',
              maxLines: 2,
              overflow: TextOverflow.ellipsis,),
              leading: CircleAvatar(),
              trailing: Text('10.20'),
              dense: true,
              tileColor: Colors.green,
              // contentPadding: EdgeInsets.symmetric(vertical: 20),
            ),
            Divider(color: Colors.black),
            ListTile(
              title: Text('Gayuh Widyanata'),
              subtitle: Text('Hai Apa Kabar?ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd',
              maxLines: 2,
              overflow: TextOverflow.ellipsis,),
              leading: CircleAvatar(),
              trailing: Text('10.20'),
              dense: true,
              tileColor: Colors.green,
              // contentPadding: EdgeInsets.symmetric(vertical: 20),
            ),
            Divider(color: Colors.black),
            ListTile(
              title: Text('Gayuh Widyanata'),
              subtitle: Text('Hai Apa Kabar?ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd',
              maxLines: 2,
              overflow: TextOverflow.ellipsis,),
              leading: CircleAvatar(),
              trailing: Text('10.20'),
              dense: true,
              tileColor: Colors.green,
              // contentPadding: EdgeInsets.symmetric(vertical: 20),
            ),
            Divider(color: Colors.black),
            ListTile(
              title: Text('Gayuh Widyanata'),
              subtitle: Text('Hai Apa Kabar?ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd',
              maxLines: 2,
              overflow: TextOverflow.ellipsis,),
              leading: CircleAvatar(),
              trailing: Text('10.20'),
              dense: true,
              tileColor: Colors.green,
              // contentPadding: EdgeInsets.symmetric(vertical: 20),
            ),
            Divider(color: Colors.black),
            ListTile(
              title: Text('Gayuh Widyanata'),
              subtitle: Text('Hai Apa Kabar?ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd',
              maxLines: 2,
              overflow: TextOverflow.ellipsis,),
              leading: CircleAvatar(),
              trailing: Text('10.20'),
              dense: true,
              tileColor: Colors.green,
              // contentPadding: EdgeInsets.symmetric(vertical: 20),
            ),
            Divider(color: Colors.black),
            ListTile(
              title: Text('Gayuh Widyanata'),
              subtitle: Text('Hai Apa Kabar?ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd',
              maxLines: 2,
              overflow: TextOverflow.ellipsis,),
              leading: CircleAvatar(),
              trailing: Text('10.20'),
              dense: true,
              tileColor: Colors.green,
              // contentPadding: EdgeInsets.symmetric(vertical: 20),
            ),
            Divider(color: Colors.black),
            ListTile(
              title: Text('Gayuh Widyanata'),
              subtitle: Text('Hai Apa Kabar?ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd',
              maxLines: 2,
              overflow: TextOverflow.ellipsis,),
              leading: CircleAvatar(),
              trailing: Text('10.20'),
              dense: true,
              tileColor: Colors.green,
              // contentPadding: EdgeInsets.symmetric(vertical: 20),
            ),
            Divider(color: Colors.black),
            ListTile(
              title: Text('Gayuh Widyanata'),
              subtitle: Text('Hai Apa Kabar?ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd',
              maxLines: 2,
              overflow: TextOverflow.ellipsis,),
              leading: CircleAvatar(),
              trailing: Text('10.20'),
              dense: true,
              tileColor: Colors.green,
              // contentPadding: EdgeInsets.symmetric(vertical: 20),
            ),
            Divider(color: Colors.black),
          ],
        ),
      ),
    );
  }
}